#jwt:
#  secret: YourJWTSecretKey
#  expiration: 86400000

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database_name
#    username: your_username
#    password: your_password
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
 #     hibernate:
 #       dialect: org.hibernate.dialect.PostgreSQLDialect
 # security:
 #   filter:
 #     order: 10

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  security:
    user:
      name: admin
      password: adminpassword

# Добавьте эту настройку, чтобы отключить предупреждение open-in-view
spring.jpa.open-in-view: false